### ISSUE TITLE
Error 500 when using tagmanager in v29+

### ISSUE THREAD

**Issue by roeldeb** [Kentico/xperience-by-kentico-tag-manager#21]
**Describe the bug**
Module is not working in v29+
When accessing the module in admin, or the configuration for the tagmanager, a 500 error occurs.

**To Reproduce**
1. Go to 'Tag management'
2. See error

In configuration
1. Go to 'Configuration' - 'Tag management'
2. See error

**Exception**
Description
An unhandled exception has occurred while executing the request.
Message: Method not found: 'System.Collections.Generic.IList<Kentico.Xperience.Admin.Base.ActionConfiguration> Kentico.Xperience.Admin.Base.TableActionConfigurationExtensions.AddDeleteAction(System.Collections.Generic.IList<Kentico.Xperience.Admin.Base.ActionConfiguration>, System.String, System.String, System.Action<Kentico.Xperience.Admin.Base.ActionConfiguration,CMS.Base.IDataContainer>)'.
Exception type: System.MissingMethodException
Stack trace:
at Kentico.Xperience.TagManager.Admin.CodeSnippetListingPage.ConfigurePage()
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Kentico.Xperience.TagManager.Admin.CodeSnippetListingPage.ConfigurePage()
at Kentico.Xperience.Admin.Base.PageInvokerBase.GetPageAndExtenders(UITreeNode node, PageRouteValues routeValues)
at Kentico.Xperience.Admin.Base.PageInvoker.InvokePage(String path)
at Kentico.Xperience.Admin.Base.KenticoAdministrationController.GetPageConfiguration(PageConfigurationRequestModel pageConfigurationRequest)

**Library Version**
2.0.1

**Comment by mwiseley-wakefly** [comment]
We are seeing this same issue. Currently preventing us from using it.

**Comment by liparova** [comment]
Thank you for notifying us of the issue. We will proceed to troubleshoot and keep you updated on our analysis.

**Comment by bkapustik** [comment]
Hello, we have created a GitHub release 3.0.0 and new NuGet package version, which solves this issue.
